# This file was generated by GoReleaser. DO NOT EDIT.
cask "bdcli" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "581b321e015413c2ba2be2dc168f4f48912ad9d35938987d714abad0e9dba013"
      url "https://github.com/BetterDiscord/cli/releases/download/v#{version}/bdcli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9c439f28d19b883f1e9572c3f540039ea1658f7d6255663c9d371a1e68a502dd"
      url "https://github.com/BetterDiscord/cli/releases/download/v#{version}/bdcli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b4eaad572c0d0445d7e305cb045122a27aacb2c2b6e862130a6def00580b5268"
      url "https://github.com/BetterDiscord/cli/releases/download/v#{version}/bdcli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "530628185609a121f57c7af9818000ce2735b611d432f936b2a55e595b9dc1bc"
      url "https://github.com/BetterDiscord/cli/releases/download/v#{version}/bdcli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bdcli"
  desc "A cross-platform CLI for managing BetterDiscord."
  homepage "https://betterdiscord.app/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bdcli"
  bash_completion "completions/bdcli.bash"
  fish_completion "completions/bdcli.fish"
  zsh_completion "completions/bdcli.zsh"

  # No zap stanza required

end
