# This file was generated by GoReleaser. DO NOT EDIT.
cask "bdcli" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "78abaa9ba6a9428b0cbd6eea10cc2e2a9f7f48aa5c9aa773a42ae26aa92ea76f"
      url "https://github.com/BetterDiscord/cli/releases/download/v#{version}/bdcli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a69ab1f1e3b5faeded11b033f47008825c3e45243801c555046dc86c1998d560"
      url "https://github.com/BetterDiscord/cli/releases/download/v#{version}/bdcli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "317c607294fa95fda694d33796a693b49433f7496e10e3845120a6de432b3a5c"
      url "https://github.com/BetterDiscord/cli/releases/download/v#{version}/bdcli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "df0a97f64be42abed3bb534c7770207ca78f79e5f82eaeb6027f2cbd46e0df44"
      url "https://github.com/BetterDiscord/cli/releases/download/v#{version}/bdcli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "bdcli"
  desc "A cross-platform CLI for managing BetterDiscord."
  homepage "https://betterdiscord.app/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bdcli"

  generate_completions_from_executable "bdcli", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required
end
