# This file was generated by GoReleaser. DO NOT EDIT.
cask "bdcli" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "d48ba7ca2a5b3733a0ee15824ff37f169fe7a42ac86f7813ce730b4dfc458e7e"
      url "https://github.com/BetterDiscord/cli/releases/download/v#{version}/bdcli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c894e4869e939586459427008ca2bc8107cf4a28416f3eb3f44139b498602edd"
      url "https://github.com/BetterDiscord/cli/releases/download/v#{version}/bdcli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "77c39eecd4b3eba0a27f5a3806a23d6be7a21f961afda661374ff8223ffefeab"
      url "https://github.com/BetterDiscord/cli/releases/download/v#{version}/bdcli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "84eb6b8c4d3037e3890638d583d7c10f0c40f8eebe2b0a680c5c30fddea757f4"
      url "https://github.com/BetterDiscord/cli/releases/download/v#{version}/bdcli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bdcli"
  desc "A cross-platform CLI for managing BetterDiscord."
  homepage "https://betterdiscord.app/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bdcli"
  generate_completions_from_executable "bdcli", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required

end
