# This file was generated by GoReleaser. DO NOT EDIT.
cask "betterdiscord-installer" do
  app "BetterDiscord Installer.app"

  version "2.0.0"

  on_macos do
    sha256 "7acd4d8d1408ec2100de7de2a2c19103874e127f9e995bcb46fa06dc809fc5fd"
    url "https://github.com/BetterDiscord/Installer/releases/download/v#{version}/BetterDiscord-Installer-Mac.zip"
  end

  name "betterdiscord-installer"
  desc "A simple standalone program to install, repair, and uninstall BetterDiscord."
  homepage "https://betterdiscord.app/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "#{appdir}/BetterDiscord Installer.app/Contents/MacOS/BetterDiscord-Installer"

  # No zap stanza required
end
